// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkMGgoxxm-KgZ4YIZX1oKUTYxkVBKJjAA',
    appId: '1:55506097521:web:c59afb2d9ec48744db92d0',
    messagingSenderId: '55506097521',
    projectId: 'zap-list-e46a4',
    authDomain: 'zap-list-e46a4.firebaseapp.com',
    storageBucket: 'zap-list-e46a4.firebasestorage.app',
    measurementId: 'G-8L0YKVFSTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaNVfCUtoRr4NsgtMrtlq5CEIEq8oOSPs',
    appId: '1:55506097521:android:af241986a85d2ca0db92d0',
    messagingSenderId: '55506097521',
    projectId: 'zap-list-e46a4',
    storageBucket: 'zap-list-e46a4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkMGgoxxm-KgZ4YIZX1oKUTYxkVBKJjAA',
    appId: '1:55506097521:web:8521cea6c6e21fc3db92d0',
    messagingSenderId: '55506097521',
    projectId: 'zap-list-e46a4',
    authDomain: 'zap-list-e46a4.firebaseapp.com',
    storageBucket: 'zap-list-e46a4.firebasestorage.app',
    measurementId: 'G-37F65ZCSDT',
  );

}